### ISSUE TITLE
Java Chat Tutorial Doesn't  Work

### ISSUE THREAD

**Issue by zlavallee** [mixer/developer-docs#66]
After following the Java chat tutorial found here:

https://dev.mixer.com/guides/chat/chatbot

I get the following error:

Exception in thread "main" java.util.concurrent.ExecutionException: com.mixer.api.http.HttpBadResponseException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at test.MixerBot.main(MixerBot.java:30)
Caused by: com.mixer.api.http.HttpBadResponseException
	at com.mixer.api.http.MixerHttpClient.handleResponse(MixerHttpClient.java:231)
	at com.mixer.api.http.MixerHttpClient.handleRequest(MixerHttpClient.java:218)
	at com.mixer.api.http.MixerHttpClient$2.call(MixerHttpClient.java:205)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ProbablePrime** [comment]
Could you take a look at #48 ? I might have fixed the same issue here.

Thanks!

**Comment by zlavallee** [comment]
Yeah. Thanks.
